### ISSUE TITLE
Nav links shown off screen on mobile. Also Nav does not close once opened on mobile

### ISSUE THREAD

**Issue by johnlandish** [johndatserakis/vue-navigation-bar#4] opened 2019-10-18 21:59 UTC
Nav links shown off screen on mobile. Also Nav does not close once opened on mobile

**Comment by johndatserakis** [comment] 2019-10-19 19:42
Hi there!

I just ran a few tests on a site I have in production live that's using this component - [RSVP Keeper](https://www.rsvpkeeper.com). Everything seems to be working fine and I can't really reproduce the issues you're having.

Can you provide some more detail about what browser you're using when you're getting the nav links to show up off screen? Also - if they're any steps you took to reproduce the issue please share them.

If you could maybe show me your `navbarOptions` object I could take a look. Also please make sure you're upgraded to the latest version as there have been a few updates recently.

Standing by! Thank you.

**Comment by johndatserakis** [comment] 2020-04-09 02:58
Closing for now, let me know if the issue is still occurring. Thank you.

**Closed as completed by johndatserakis** 2020-04-09 02:58 UTC
